name: CI
on:
    push:
        branches: [main]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '16.x'
            - name: Install Sanity
              run: |
                  npm install -g @sanity/cli
            - name: Install dependencies
              run: |
                  npm install
            - name: Deploy Sanity
              run: |
                  SANITY_AUTH_TOKEN="${{ secrets.SANITY_AUTH_TOKEN }}" npm run deploy